{{- if or (not (empty .Values.secretEnvs)) (not (empty .Values.secretEnvsString)) }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" "secret-envs" "context" $) }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
    {{- include "helpers.app.gitopsLabels" (dict "context" $) | nindent 4 }}
  annotations:
    {{- include "helpers.app.hooksAnnotations" $ | nindent 4 }}
    {{- include "helpers.app.genericAnnotations" $ | nindent 4 }}
    {{- include "helpers.app.gitopsAnnotations" (dict "context" $) | nindent 4 }}
data:
  {{- include "helpers.secrets.render" (dict "value" (include "helpers.tplvalues.render" (dict "value" .Values.secretEnvsString "context" $)) "context" $) | nindent 2 }}
  {{- include "helpers.secrets.render" (dict "value" (include "helpers.tplvalues.render" (dict "value" .Values.secretEnvs "context" $)) "context" $) | nindent 2 }}
{{ end }}

{{- range $name := keys (.Values.secrets | default dict) | sortAlpha }}
{{- $secret := get $.Values.secrets $name -}}
{{- if and (eq "true" (include "helpers.resources.isEnabled" (dict "value" $secret))) (ne $name "secret-envs") }}
---
apiVersion: v1
kind: Secret
type: {{ $secret.type | default "Opaque" }}
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $name "context" $) }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
    {{- include "helpers.app.gitopsLabels" (dict "context" $ "value" $secret) | nindent 4 }}
    {{- with $secret.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
  annotations:
    {{- include "helpers.app.hooksAnnotations" $ | nindent 4 }}
    {{- include "helpers.app.genericAnnotations" $ | nindent 4 }}
    {{- include "helpers.app.gitopsAnnotations" (dict "context" $ "value" $secret) | nindent 4 }}
    {{- with $secret.annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
data:
  {{- include "helpers.secrets.render" (dict "value" (include "helpers.tplvalues.render" (dict "value" $secret.data "context" $)) "context" $) | nindent 2 }}
{{ end }}
{{ end }}

{{- range $name := keys (.Values.imagePullSecrets | default dict) | sortAlpha }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
    {{- include "helpers.app.gitopsLabels" (dict "context" $) | nindent 4 }}
  annotations:
    {{- include "helpers.app.hooksAnnotations" $ | nindent 4 }}
    {{- include "helpers.app.genericAnnotations" $ | nindent 4 }}
    {{- include "helpers.app.gitopsAnnotations" (dict "context" $) | nindent 4 }}
data:
  {{- include "helpers.secrets.render" (dict "value" (include "helpers.tplvalues.render" (dict "value" (printf ".dockerconfigjson: %v" (get $.Values.imagePullSecrets $name)) "context" $)) "context" $) | nindent 2 }}
{{ end }}

{{- range $name := keys (.Values.sealedSecrets | default dict) | sortAlpha }}
{{- $secret := get $.Values.sealedSecrets $name -}}
{{- if eq "true" (include "helpers.resources.isEnabled" (dict "value" $secret)) }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $name "context" $) }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
    {{- include "helpers.app.gitopsLabels" (dict "context" $ "value" $secret) | nindent 4 }}
    {{- with $secret.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
  annotations:
    {{- include "helpers.app.hooksAnnotations" $ | nindent 4 }}
    {{- include "helpers.app.genericAnnotations" $ | nindent 4 }}
    {{- include "helpers.app.gitopsAnnotations" (dict "context" $ "value" $secret) | nindent 4 }}
    {{- with $secret.annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
spec:
  encryptedData:
    {{- include "helpers.secrets.renderSealed" (dict "value" (include "helpers.tplvalues.render" (dict "value" $secret.encryptedData "context" $)) "context" $) | nindent 4 }}
  template:
    metadata:
      name: {{ include "helpers.app.fullname" (dict "name" $name "context" $) }}
      namespace: {{ $.Release.Namespace | quote }}
      labels:
        {{- include "helpers.app.labels" $ | nindent 8 }}
        {{- include "helpers.app.gitopsLabels" (dict "context" $ "value" $secret) | nindent 8 }}
        {{- with $secret.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}{{- end }}
      annotations:
        {{- include "helpers.app.genericAnnotations" $ | nindent 8 }}
        {{- include "helpers.app.gitopsAnnotations" (dict "context" $ "value" $secret) | nindent 8 }}
        {{- with $secret.annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}{{- end }}
{{ end }}
{{- end }}
