{{- $general := $.Values.serviceAccountGeneral | default dict -}}
{{- $serviceAccounts := dict -}}
{{- if kindIs "string" .Values.serviceAccount -}}
{{- $serviceAccounts = fromYaml .Values.serviceAccount | default dict -}}
{{- else if kindIs "map" .Values.serviceAccount -}}
{{- $serviceAccounts = .Values.serviceAccount -}}
{{- end -}}
{{- range $name := keys $serviceAccounts | sortAlpha }}
{{- $account := get $serviceAccounts $name -}}
{{- if eq "true" (include "helpers.resources.isEnabled" (dict "value" $account)) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $name "context" $) }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
    {{- include "helpers.app.gitopsLabels" (dict "context" $ "general" $general "value" $account) | nindent 4 }}
    {{- with $general.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
    {{- with $account.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
  annotations:
    {{- include "helpers.app.annotations" (dict "context" $ "general" $general "value" $account) | nindent 4 }}

{{- if $account.role }}
{{- if $account.role.rules }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $account.role.name "context" $) }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
    {{- include "helpers.app.gitopsLabels" (dict "context" $ "general" $general "value" $account) | nindent 4 }}
    {{- with $general.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
    {{- with $account.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
  annotations:
    {{- include "helpers.app.annotations" (dict "context" $ "general" $general "value" $account) | nindent 4 }}
rules:
{{ include "helpers.tplvalues.render" (dict "value" $account.role.rules "context" $) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $account.role.name "context" $) }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
    {{- include "helpers.app.gitopsLabels" (dict "context" $ "general" $general "value" $account) | nindent 4 }}
    {{- with $general.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
    {{- with $account.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
  annotations:
    {{- include "helpers.app.annotations" (dict "context" $ "general" $general "value" $account) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "helpers.app.fullname" (dict "name" $account.role.name "context" $) }}
subjects:
  - kind: ServiceAccount
    name: {{ include "helpers.app.fullname" (dict "name" $name "context" $) }}
    namespace: {{ $.Release.Namespace | quote }}
{{- else }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $account.role.name "context" $) }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
    {{- include "helpers.app.gitopsLabels" (dict "context" $ "general" $general "value" $account) | nindent 4 }}
    {{- with $general.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
    {{- with $account.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
  annotations:
    {{- include "helpers.app.annotations" (dict "context" $ "general" $general "value" $account) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $account.role.name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "helpers.app.fullname" (dict "name" $name "context" $) }}
    namespace: {{ $.Release.Namespace | quote }}
{{- end }}
{{- end }}

{{- if $account.clusterRole }}
{{- if $account.clusterRole.rules }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $account.clusterRole.name "context" $) }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
    {{- include "helpers.app.gitopsLabels" (dict "context" $ "general" $general "value" $account) | nindent 4 }}
    {{- with $general.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
    {{- with $account.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
  annotations:
    {{- include "helpers.app.annotations" (dict "context" $ "general" $general "value" $account) | nindent 4 }}
rules:
{{ include "helpers.tplvalues.render" (dict "value" $account.clusterRole.rules "context" $) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $account.clusterRole.name "context" $) }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
    {{- include "helpers.app.gitopsLabels" (dict "context" $ "general" $general "value" $account) | nindent 4 }}
    {{- with $general.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
    {{- with $account.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
  annotations:
    {{- include "helpers.app.annotations" (dict "context" $ "general" $general "value" $account) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "helpers.app.fullname" (dict "name" $account.clusterRole.name "context" $) }}
subjects:
  - kind: ServiceAccount
    name: {{ include "helpers.app.fullname" (dict "name" $name "context" $) }}
    namespace: {{ $.Release.Namespace | quote }}
{{- else }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $account.clusterRole.name "context" $) }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
    {{- include "helpers.app.gitopsLabels" (dict "context" $ "general" $general "value" $account) | nindent 4 }}
    {{- with $general.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
    {{- with $account.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
  annotations:
    {{- include "helpers.app.annotations" (dict "context" $ "general" $general "value" $account) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $account.clusterRole.name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "helpers.app.fullname" (dict "name" $name "context" $) }}
    namespace: {{ $.Release.Namespace | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
