---
repos:
  - repo: local
    hooks:
      - id: helm-docs
        name: Helm Docs
        entry: scripts/helm-docs.sh
        language: script
        files: (README\.md\.gotmpl|(Chart|requirements|values)\.yaml)$
        pass_filenames: false
