generic:
  podSecurityContext:
    runAsNonRoot: true

services:
  app-web:
    type: ClusterIP
    ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 8080

deployments:
  app:
    securityContext:
      # mergeWithGeneric will merge generic.podSecurityContext.runAsNonRoot into here (and mergeWithGeneric itself will be removed).
      mergeWithGeneric: true
      runAsUser: 1000
      runAsGroup: 3000
      fsGroup: 2000
    containers:
    - name: app
      image: containous/whoami
      imageTag: v1.5.0
      resources:
        limits:
          cpu: 10m
          memory: 128Mi
        requests:
          cpu: 1m
          memory: 64Mi
      args:
        - --port
        - "8080"
      ports:
        - name: web
          containerPort: 8080
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
