defaultImage: nginx
defaultImageTag: latest
defaultImagePullPolicy: "IfNotPresent"

deployments:
  nginx:
    replicas: 2
    serviceAccountName: deployer
    containers:
      - name: nginx
        image: nginx
        imageTag: 1.19
        imagePullPolicy: Always
