defaultImage: nginx
defaultImagePullPolicy: SomeTimes

deployments:
  nginx:
    replicas: as-many-as-possible
    serviceAccountName: deployer
    containers:
      - name: nginx
        image: nginx
        imageTag: 1.19
        pullPolicy: Always
