{{- $general := $.Values.daemonSetsGeneral | default dict -}}
{{- $modeEnabled := eq "true" (include "helpers.workloads.modeEnabled" (dict "kind" "daemonset" "context" $)) -}}
{{- if $modeEnabled }}
{{- range $name := keys (.Values.daemonSets | default dict) | sortAlpha }}
{{- $daemonSet := get $.Values.daemonSets $name -}}
{{- if eq "true" (include "helpers.resources.isEnabled" (dict "value" $daemonSet)) }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $name "context" $) }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
    {{- include "helpers.app.gitopsLabels" (dict "context" $ "general" $general "value" $daemonSet) | nindent 4 }}
    {{- with $general.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
    {{- with $daemonSet.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
  annotations:
    {{- include "helpers.app.annotations" (dict "context" $ "general" $general "value" $daemonSet) | nindent 4 }}
spec:
  {{- with $daemonSet.strategy }}
  updateStrategy: {{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
  {{- end }}
  {{- with $daemonSet.minReadySeconds }}
  minReadySeconds: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helpers.app.selectorLabels" $ | nindent 6 }}
      {{- with $daemonSet.extraSelectorLabels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 6 }}{{- end }}
  template:
    metadata:
      labels:
        {{- include "helpers.app.selectorLabels" $ | nindent 8 }}
        {{- with $daemonSet.extraSelectorLabels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}{{- end }}
        {{- with $.Values.generic.podLabels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}{{- end }}
        {{- with $general.podLabels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}{{- end }}
        {{- with $daemonSet.podLabels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}{{- end }}
      annotations:
        {{- include "helpers.workloads.podAnnotations" (dict "context" $ "general" $general "value" $daemonSet) | nindent 8 }}
    spec:
      {{- include "helpers.pod" (dict "value" $daemonSet "general" $general "name" $name "extraLabels" $daemonSet.extraSelectorLabels "context" $) | nindent 6 }}
{{- end }}
{{- end }}
{{- end }}
