{{- $general := $.Values.podsGeneral | default dict -}}
{{- $modeEnabled := eq "true" (include "helpers.workloads.modeEnabled" (dict "kind" "pod" "context" $)) -}}
{{- if $modeEnabled }}
{{- range $name := keys (.Values.pods | default dict) | sortAlpha }}
{{- $pod := get $.Values.pods $name -}}
{{- if eq "true" (include "helpers.resources.isEnabled" (dict "value" $pod)) }}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $name "context" $) }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
    {{- include "helpers.app.gitopsLabels" (dict "context" $ "general" $general "value" $pod) | nindent 4 }}
    {{- with $general.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
    {{- with $pod.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
    {{- with $.Values.generic.podLabels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
    {{- with $general.podLabels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
    {{- with $pod.podLabels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
  annotations:
    {{- include "helpers.app.genericAnnotations" $ | nindent 4 }}
    {{- include "helpers.app.gitopsAnnotations" (dict "context" $ "general" $general "value" $pod) | nindent 4 }}
    {{- include "helpers.workloads.autoChecksumAnnotations" (dict "context" $ "general" $general "value" $pod) | nindent 4 }}
    {{- with $general.annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
    {{- with $pod.annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
    {{- with $.Values.generic.podAnnotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
    {{- with $general.podAnnotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
    {{- with $pod.podAnnotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
spec:
  {{- include "helpers.pod" (dict "value" $pod "general" $general "name" $name "extraLabels" $pod.extraSelectorLabels "context" $) | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
