{{- if .Values.cronJobs -}}
{{- $general := $.Values.cronJobsGeneral -}}
{{- $cronJobs := list -}}
{{- if kindIs "string" .Values.cronJobs -}}
{{- $cronJobs = fromYaml .Values.cronJobs -}}
{{- else if kindIs "map" .Values.cronJobs -}}
{{- $cronJobs = .Values.cronJobs -}}
{{- end -}}
{{- range $name, $job := $cronJobs }}
{{- $cjName := include "helpers.app.fullname" (dict "name" $name "context" $) }}
---
apiVersion: {{ include "helpers.capabilities.cronJob.apiVersion" $ }}
kind: CronJob
metadata:
  name: {{ $cjName }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
    {{- with $general.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
    {{- with .labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
  annotations:
    {{- include "helpers.app.genericAnnotations" $ | indent 4 }}
    {{- with $general.annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
    {{- with .annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
spec:
  schedule: {{ include "helpers.tplvalues.render" (dict "value" .schedule "context" $) | quote }}
  {{- if any .timeZone $general.timeZone }}
  timeZone: {{ default $general.timeZone .timeZone }}
  {{- end }}
  concurrencyPolicy: {{ default "Allow" $general.concurrencyPolicy .concurrencyPolicy }}
  {{- if any .startingDeadlineSeconds $general.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ default $general.startingDeadlineSeconds .startingDeadlineSeconds }}
  {{- end }}
  {{- if any .successfulJobsHistoryLimit $general.successfulJobsHistoryLimit}}
  successfulJobsHistoryLimit: {{ default $general.successfulJobsHistoryLimit .successfulJobsHistoryLimit }}
  {{- end }}
  {{- if any .failedJobsHistoryLimit $general.failedJobsHistoryLimit}}
  failedJobsHistoryLimit: {{ default $general.failedJobsHistoryLimit .failedJobsHistoryLimit }}
  {{- end }}
  jobTemplate:
    spec:
      {{- include "helpers.job" (dict "value" . "general" $general "name" $name "context" $) | indent 6 }}

{{- if .commandDurationAlert }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cronjob-{{ $cjName }}
  labels:
    prometheus: k8s
    role: alert-rules
  namespace: metrics
spec:
  groups:
  - name: "cronJobs_rules"
    interval: 1m # period check for alerts
    rules:
    - alert: "cronjob-{{ $cjName }}-too-long-execution"
      expr: '((time() - kube_job_status_start_time{namespace="{{ $.Release.Namespace }}", job_name=~"{{ $cjName }}-.*"}) and kube_job_status_active{namespace="{{ $.Release.Namespace }}", job_name=~"{{ $cjName }}-.*"} == 1) > {{ .commandDurationAlert }}'
      for: 3m
      labels:
        severity: warning
      annotations:
        message: "CronJob {{ $.Release.Namespace }}/{{ $cjName }} is taking more than {{ .commandDurationAlert }} to complete"
{{- end }}
{{- end }}
{{- end }}
