{{- if .Values.jobs -}}
{{- $general := $.Values.jobsGeneral -}}
{{- $jobs := list -}}
{{- if kindIs "string" .Values.jobs -}}
{{- $jobs = fromYaml .Values.jobs -}}
{{- else if kindIs "map" .Values.jobs -}}
{{- $jobs = .Values.jobs -}}
{{- end -}}
{{- range $name, $job := $jobs }}
{{- $jobName := include "helpers.app.fullname" (dict "name" $name "context" $) }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $jobName }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
    {{- with .labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
  annotations:
    {{- include "helpers.app.genericAnnotations" $ | indent 4 }}
    {{- with .annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
spec:
  {{- include "helpers.job" (dict "value" . "general" $general "name" $name "context" $) | indent 2 }}

{{- if .commandDurationAlert }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: job-{{ $jobName }}
  labels:
    prometheus: k8s
    role: alert-rules
  namespace: metrics
spec:
  groups:
  - name: "jobs_rules"
    interval: 1m # period check for alerts
    rules:
    - alert: "job-{{ $jobName }}-too-long-execution"
      expr: '((time() - kube_job_status_start_time{namespace="{{ $.Release.Namespace }}", job_name=~"{{ $jobName }}-.*"}) and kube_job_status_active{namespace="{{ $.Release.Namespace }}", job_name=~"{{ $jobName }}-.*"} == 1) > {{ .commandDurationAlert }}'
      for: 3m
      labels:
        severity: warning
      annotations:
        message: "Job {{ $.Release.Namespace }}/{{ $jobName }} is taking more than {{ .commandDurationAlert }} to complete"
{{- end }}
{{- end }}
{{- end }}
